### ISSUE TITLE
seperate wipers

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [Frvetz/FS22_ManualWipers#1]
hi, 
is it possible to make inputaction for front and back wiper separated from each other?
So that you can turn on just one maybe.

**Comment by Frvetz** [comment]
Hi,

I just had a closer look at the function of the wipers from the base game and I think I have found something that looks promising :D I will take a closer look when I find the time and then let you know if I have managed to get something to work :D 👍 

Kind regards,
Gerrit (frvetz)

**Comment by SbSh-DNA-ModDing** [comment]
okay nice.
actually it works over global wiper state... and I know that there is a section like indicies like it is with the attacher.
If id 1 or 2 is back or front or reversed, thats not relevant. But I don't know - some machines has wipers on the side.... perhaps the same id as back?   Thanks for have an eye on it.

**Comment by Frvetz** [comment]
Exactly, the table with the indexes (like the attacher) were my idea as well. If I have understood the wiper function of Giants correctly, each index (one index = one wiper) is queried with a loop and then activated, if I now replace the loop with numbers (1, 2, 3...), each wiper should be activated individually.

**Comment by SbSh-DNA-ModDing** [comment]
btw.. in your script is one "if" less

some mods get this in log:
2022-12-13 22:06 Error: Running LUA method 'update'.
C:/Users/SbSh/Documents/My Games/FarmingSimulator2022/mods/FS22_ManualWipers/ManualWipers.lua:106: attempt to index field 'spec_ManualWipers' (a nil value)

if self.spec_ManualWipers ~= nil then
					if self.spec_ManualWipers.ButtonHit then
                                        ...
else
:set back to vanilla::  or something   :


I think the issue is, when the window incl. the wiper is in a configuration set. For Example, there are two window sets, one wiper at the top. the other at bottom.




WiperAnims example of the vanilla vario900
`        <animation name="wiperFrontAnimation">
            <part node="wiperFront" startTime="0.0" endTime="2.5" startRot="0 0 0" endRot="0 -8 155" />
            <part node="wiperFront" startTime="2.5" endTime="5.0" startRot="0 -8 155" endRot="0 0 300" />

            <sound template="wiper1" startTime="0" endTime="5" direction="1"   volumeScale="1.0" pitchScale="0.9" fadeOut="0.1" linkNode="wiperFront"/>
            <sound template="wiper2" startTime="0" endTime="5" direction="-1"  volumeScale="1.0" pitchScale="0.9" fadeOut="0.1" linkNode="wiperFront"/>
        </animation>

        <animation name="wiperSideAnimation">
            <part node="wiperSide" startTime="0.0" endTime="2.5"  startRot="0 0 0" endRot="0 -3 120" />
            <part node="wiperSide" startTime="2.5" endTime="5.0"  startRot="0 -3 120" endRot="0 2 230" />

            <sound template="wiper1" startTime="0" endTime="5" direction="1"   volumeScale="0.7" pitchScale="0.7" fadeOut="0.1" linkNode="wiperSide"/>
            <sound template="wiper2" startTime="0" endTime="5" direction="-1"  volumeScale="0.7" pitchScale="0.7" fadeOut="0.1" linkNode="wiperSide"/>
        </animation>

        <animation name="wiperBackAnimation">
            <part node="wiperBack" startTime="0.0" endTime="5.0"  startRot="0 0 0" endRot="0 6 -125" />

            <sound template="wiper1" startTime="0" endTime="5" direction="1"   volumeScale="0.6" pitchScale="0.8" fadeOut="0.1" linkNode="wiperBack"/>
            <sound template="wiper2" startTime="0" endTime="5" direction="-1"  volumeScale="0.6" pitchScale="0.8" fadeOut="0.1" linkNode="wiperBack"/>
        </animation>`

alternativ.. pick the xml wipers and adjust the animspeed via script. 0 = off
`<wipers>
        <wiper animName="wiperFrontAnimation" >
            <state animSpeed="3" animPause="2.0" />
            <state animSpeed="3" animPause="0.0" />
            <state animSpeed="4.5" animPause="0.0" />
        </wiper>
        <wiper animName="wiperBackAnimation" >
            <state animSpeed="3.0" animPause="3.0" />
        </wiper>
        <wiper animName="wiperSideAnimation" >
            <state animSpeed="3.0" animPause="3.0" />
        </wiper>
    </wipers>`


just an idea to help.. I don't know if it would work. 
I tried since fs 19 a script to reduce the reverseBeepVolume.. but the engine overwrite my attribues again and again :D

**Comment by Frvetz** [comment]
Ohhh thank you for letting me know about the error!

Maybe the FS separates the wipers anyway, even though it's one animation... I'll try that out. But your ideas are great and will definitely help me! :) 
When it comes to assigning the buttons for different wipers, I think the only good and clear option is to assign different buttons for each wiper individually and then not display the buttons in the f1 menu (e.g. ctrl + 1; ctrl + 2; ctrl + 3; ...), so that the help window doesn't get extremely full...? Maybe I even find a way to have the wipers always on the same button (with getTranslation).

And regarding your idea for a script to reduce the reverseBeepVolume: If you want to I can give it a try and see if I can get it overwritten somehow? :D 👍

**Comment by SbSh-DNA-ModDing** [comment]
Yes, I don't think the key assignment needs to be visible in the F1 menu.  A "switching function" such as with the light (F) would then be an option for those who don't have that many buttons available.  I have some self-made buttons via an Audrino, I rather think that the bindings are limited by giants at some point :D


¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 About my script (attempt)... 
 here is a snippet of it:
 `--setSampleVolume(spec.samples.reverseDrive.volumeScale, 0.4)
			 -- setSampleVolume(spec.samples.reverseDrive, 0.4 * self:getCurrentSampleVolume(sample))
			 --print("LRBV Current vol: " ..self:getCurrentSampleVolume(sample))
             spec.samples.reverseDrive = nil -- dropping works = no beepsound
			 print("LRBV beep sound just dropped")
         end`
 I don't know exactly how to read out the sample for this, otherwise it could work with setSampleVolume via the SoundManager.  Only every sample I query is "nil" ... no idea.  If you could do that, you could also customize every other sample - depending on indoor / outdoor maybe even.



▓▒D▒▓▒E▒▓▒░▒▓▒░▒▓▒░▒▓▒░▒▓▒░▒▓▒░▒▓▒░▒▓
ja die Tastenbelegung braucht denke ich nicht im F1 Menü sichtbar sein. Eine "Durchschaltfunktion" wie mit dem Licht (F) wäre dann noch eine Option für die, die nicht so viele Tasten zur Verfügung habe. Ich habe über einen Audrino einige selbst gebastelte Taster, ich glaube eher das von giants die bindings irgendwann begranzt sind :D

¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
Zu meinem Script (Versuch)... 
hier ein Ausschnitt davon:
`s.o.`
[or here](https://github.com/s4t4n/FS22_EXTvolumeControl/blob/main/LowerReverseBeepVol.lua)

ich weiß nicht genau, wie ich das sample dafür auslese, ansonsten könnte das mit setSampleVolume über den SoundManager funktionieren. Nur jedes sample welches ich abfrage ist "nil" ...  keine Ahnung. Wenn man das hinbekommen würde, könnte man jedes andere Sample auch individuell anpassen - indoor / outdoor abhängig vielleicht sogar.

**Comment by Frvetz** [comment]
Ich nehme jetzt mal an du sprichst auch deutsch? :D 

Durchschalten ist auf jeden Fall auch eine sehr gute Idee jaa! 👍 Vielleicht kann man ja auch in den Einstellungen einstellbar machen, ob man für jeden Scheibenwischer eine eigene Taste benutzen möchte, oder ob man so eine Durchschaltfunktion nutzen möchte… mal schauen

Zu deinem Script:
Ich hatte eher daran gedacht nach der Giants Funktion für den ReverseSound zu suchen und diese dann mit OverwrittenFunction zu überschreiben 🤔 aber nicht sicher, ob das funktioniert bzw. ob man den Teil überhaupt findet, wo Giants den Befehl gibt den ReverseSound zu spielen…

**Comment by SbSh-DNA-ModDing** [comment]
jup^^.. am einfachsten wäre, einfach Bspw. 4 inputBindings   id1 wiper1, id2 wiper2, id3 wiper3  & id4 (1-3) zum durchschalten, was man davon nicht nutzen möchte, wird einfach nicht belegt. Die F Lichtvariante macht ja nichts anders.. state 0, 0 1, 0 1 2 bis X usw.
Vordefinierte inputs sind auch oft schwierig bei Doppelbelegungen. LS reagiert da ja allergisch drauf. 


Die OverrittenFuction kenn sich gar nicht.. hab ich zwar schon mal gesehen, dachte aber daß sei eine eigene Funktion von den moddern...  ein wenig Programmieren kann ich, ich find' mich nur nicht zurecht im LS, alles etwas merkwürdig angeordnet und keine vollständigen var tables, gleiche cat.'s sind überall verstreut. Für die script doku benötigt man noch ein Handbuch xD

ich hab dich auf jeden Fall mal mit in mein Script gezogen... (hoffe das funktioniert so, hab ich noch nie gemacht.)
Wenn meine Theorie richtig ist, müsstest du dort alles editieren können.

**Comment by Frvetz** [comment]
Yes, ich kann alles bearbeiten 👍 da werde ich mich dann wahrscheinlich in den Weihnachtsferien mal dran versuchen :D

Und so ähnlich hatte ich mir das mit den Tasten jetzt auch vorgestellt... Das mit dem "state 0, 0 1, 0 1 2 bis X" war noch ein sehr guter Hinweis!! Das hatte ich irgendwie absolut nicht auf dem Schirm, dass das so funktioniert xD
Das einzige, wo ich jetzt was anderes im Kopf hatte, war, dass man in den Einstellungen was reinmacht, um einzustellen welche Möglichkeit man möchte (einzelne Tasten oder durchschalten).

**Comment by SbSh-DNA-ModDing** [comment]
mh ich mein' klar.. Benutzerfreundlicher wäre es auf jeden Fall, aber eben auch umständlicher.. wenn man es einmal drin hat - okay...   nur dann muss es auch sp / mp (serverside und/oder clientside) gespeichert werden. Nicht wie manualAttach.. Client SP funktioniert da, mp Server nicht :D 
Aber da kann man sich denke/hoffe ich, einiges bei anderen "abgucken".. 

btw. mit dem easyDev Tool script kann man in den Einstellungen auch den rain bzw. den wiper Zustand einstellen:
Das geht da von Regensensor & aus bis Zustand 12. Keine Ahung ob das was zu sagen hat, oder von dem Script was eigenes ist. Unterschiede zw. 1-12 konnte ich nicht feststellen.

**Comment by Frvetz** [comment]
Das im EasyDev hab ich auch gesehen, hab es mir aber ehrlich gesagt nicht genauer angeschaut, sondern nur geschaut was die Einstellung im Spiel macht.

Und wegen der Einstellung, ob Durchschalten oder einzelne Belegungen: das hinzubekommen und auch zwischen Server <-> Client zu synchronisieren ist mittlerweile kein Problem mehr, hauptsächlich weil ich schon ein Script gemacht habe, wo genau sowas eingebaut ist und was auch korrekt zwischen Server <-> Client synchronisiert 👍 heißt ich kann die Teile einfach copy-pasten

Benutzt du zufällig Discord? Das würde das hier, denke ich, ein wenig leichter machen :D (frvetz#4670)

**Comment by SbSh-DNA-ModDing** [comment]
ja, habe dich damals schon mal auf'm discord gesucht wegen SDF xD
#6401
